### PR TITLE
Fix two issues

### PR DESCRIPTION
**Pull request by stoneChen**
1. #4 and relevant https://github.com/michael-ciniawsky/postcss-load-config/pull/100
2. #11 

#4 it confused me quite a long time too.
#11 is noisy.

Wait for the next release of npm package😁

### CODE REVIEW

**Comment by stoneChen** [comment]
@giuseppeg Hi, please consider my PR,  I am waiting for your next release😁

**Comment by giuseppeg** [comment]
@stoneChen ouch sorry I didn't see this. I will take a look at it this week (I've been busy at work :)

**Comment by giuseppeg** [comment]
@stoneChen published! Thanks for the PR and sorry for the delay

**Comment by stoneChen** [comment]
@giuseppeg Thank you for merging!

**Pull request merged**
