### PR TITLE
Support custom config file path, close: #23

### PR DESCRIPTION
**Pull request by leecade**
mentioned it in README

### CODE REVIEW

**Comment by leecade** [comment]
@giuseppeg @NukaPunk plz help to merge and release

**Comment by giuseppeg** [comment]
isn't postcss looking up the parent folders for postcss.config.js ?

**Comment by leecade** [comment]
> isn't postcss looking up the parent folders for postcss.config.js ?

not parent folders, sometimes we put `postcss.config.js` in the other folder, the feature is a must

**Comment by JosephScript** [comment]
I think if we're supporting a custom path we should also support a completely custom path including file name.

**Comment by leecade** [comment]
> I think if we're supporting a custom path we should also support a completely custom path including file name.

1. it's hard to implement because `postcss-load-plugins` only supports path

2. For postcss-loader, there is only one possible file name

**Comment by JosephScript** [comment]
OK I'll take a look soon.

**Comment by JosephScript** [comment]
@giuseppeg can you make me a publisher on NPM for this package? Otherwise I'll need you to publish v2.0.1.

**Comment by giuseppeg** [comment]
@NukaPunk hey sorry I will cut a release this weekend

**Comment by evolify** [comment]
Any plan to release ?

**Comment by giuseppeg** [comment]
Published. Sorry for the delay

**Pull request merged**
