### PR TITLE
[fix] Accept vars within parens (like calc())

### PR DESCRIPTION
**Pull request by corysimmons**
Couldn't figure out how to get tests to pass.

### CODE REVIEW

**Comment by a-ignatov-parc** [comment]
@corysimmons can you test this fix on this styles?

```jsx
export default function foo () {
  const num = 3;
  const padding = '10px';
  const query = 'min-width: 480px';

  return (
    <div>
      <h1>interpolation test</h1>
      <style jsx>{`
        .a:nth-child(${num}) {
          background: #f00;
        }

        .b {
          width: calc(100% / ${num});
          margin-top: ${num}px;
          padding: ${padding} ${num}px;

          &:hover {
            background: blue;
          }
          
          @media (${query}) {
            padding-bottom: 10px;
          }
        }
      `}</style>
    </div>
  );
}
```

**Comment by corysimmons** [comment]
@a-ignatov-parc Darn. https://github.com/corysimmons/styled-jsx-test doesn't work.

Getting:

```
Error in /Users/tink/Desktop/z/pages/index.js?entry
Module build failed: Error: /Users/tink/Desktop/z/pages/index.js?entry: Lexical error on line 1. Unrecognized text.
100% / _styled-jsx-placehol
-------^
    at Parser.parseError (/Users/tink/Desktop/z/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:160:21)
    at Object.parseError (/Users/tink/Desktop/z/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:310:28)
    at Object.next (/Users/tink/Desktop/z/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:565:25)
    at Object.lex (/Users/tink/Desktop/z/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:575:22)
    at Object.lex (/Users/tink/Desktop/z/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:579:25)
    at lex (/Users/tink/Desktop/z/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:197:27)
    at Parser.parse (/Users/tink/Desktop/z/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:210:26)
    at /Users/tink/Desktop/z/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/index.js:35:30
    at walk (/Users/tink/Desktop/z/node_modules/postcss-value-parser/lib/walk.js:15:13)
    at ValueParser.walk (/Users/tink/Desktop/z/node_modules/postcss-value-parser/lib/index.js:18:5)
```

**Comment by a-ignatov-parc** [comment]
Tests are failing too

**Comment by corysimmons** [comment]
If I disable `reduce-css-calc` it works!

```js
// postcss.config.js
module.exports = ctx => ({
  plugins: {
    'postcss-cssnext': {
      features: {
        calc: false,
      },
    },
  },
})
```

**Comment by corysimmons** [comment]
Yeah I mentioned tests are boinked, but it _does_ work in many conceivable contexts so I'm happy.

Maybe @giuseppeg can shed some light on what the placeholders test was trying to do and if there are any fringe cases (e.g. interaction with other styled-jsx plugins) we might be overlooking.

FWIW, I've had problems out of PostCSS calc reduction with a few PostCSS plugins I've written in the past so I just tend to disable it by default anyway.

**Comment by giuseppeg** [comment]
The test fails with `CssSyntaxError: <css input>:1:65: Unknown word` so the replacement is probably invalid and PostCSS can't parse it.

**Comment by giuseppeg** [comment]
When tweaking the regexps to cover more use cases please add tests. Also the old ones need to pass.
If you guys can help me we could try to fix the placeholders issue in styled-jsx itself so that it is not a pain in plugins to replace placeholders. I will write an issue to explain my idea.

**Comment by a-ignatov-parc** [comment]
I think we won't be able to cover all cases because preprocessors compile code in build time and we can't evaluate some constructions because of dynamic values.

As to say for `stylus` its `alpha(color, opacity)` function (and no only) won't work either.

But maybe we can handle those cases with proper warning or fallback 🤷‍♂️

**Comment by giuseppeg** [comment]
@a-ignatov-parc not sure we can do anything about dynamic styles or interpolations in general. Usually those won't be preprocessed and it is fine.

I was thinking that maybe we can figure out a way to detect the type of placeholder (before passing the plugins) and provide helpers to replace/restore placeholders.

eg `%%styled-jsx-placeholder-[block|rule|property|value]-N%%`

**Comment by a-ignatov-parc** [comment]
I can't see how this can helps us 🤔

It can get even worse because dynamic style props will break vendor prefixing for something like `display: flex` as it's already doing for style values.

```jsx
<style jsx>{`
  .container {
    display: ${props.isFlex ? 'flex' : 'block'};
  }
`}</style>
```
We wont get prefixed flex box in the example above.

**Comment by omardelarosa** [comment]
@corysimmons so I think this will only work if you leave `calc(x, y)` expressions un-processed and defer their evaluation until runtime.  There's no way to know at build-time (which is when PostCSS runs) what the values of `x` or `y` will be at runtime (which is when the props get evaluated) so for styled-jsx to work in any way, I think you have to defer evaluation until runtime.

**Comment by a-ignatov-parc** [comment]
I think at least in some cases, we can replace placeholders with [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) with enabled [`preserve`](https://github.com/MadLittleMods/postcss-css-variables#preserve-default-false) option in [`postcss-css-variables`](https://github.com/MadLittleMods/postcss-css-variables) plugin.

**Comment by JosephScript** [comment]
Hey if you still need help with this we can take another look. I've updated this plugin drastically and don't mind helping out. 

The biggest change is that `postcss-cssnext` was removed in favor of `postcss-preset-env`. Meaning at this time even basic tests won't pass. 

Let me know if this is still an issue using a valid/updated config.

**Comment by corysimmons** [comment]
Not interested in this project anymore. Leaving open in case anyone wants to do something with the code, otherwise feel free to close.

**Comment by JosephScript** [comment]
Ok thanks for the help. I understand. I only recently joined this project but I'll take a look at your PR and see if I can get it updated and working, and hopefully we can merge your contributions.

**Comment by corysimmons** [comment]
@NukaPunk np, I seem to remember having calc available had _a lot_ of cool applications in css-in-js  from grids to typography, etc. so getting this sussed might be cool. gl

**Comment by lluisrojass** [comment]
what's the purpose of commenting out placeholders? is there a specific plugin that this affects or is this a general precaution ?

cc: @corysimmons @NukaPunk  @giuseppeg

**Comment by lluisrojass** [comment]
what's the purpose of commenting out placeholders? is there a specific plugin that this affects or is this a general precaution ?

cc: @corysimmons @NukaPunk  @giuseppeg

**Comment by giuseppeg** [comment]
@lluisrojass they are not always valid placeholders. Anyway see https://github.com/giuseppeg/styled-jsx-plugin-postcss/issues/20

**Comment by JosephScript** [comment]
Hey sorry is this still valid? Should we update it and get the tests working?

**Comment by JosephScript** [comment]
Closing due to inactivity.

**Pull request closed without merging**
