### PR TITLE
Fix: deasync compatibility issue with node@9.3

### PR DESCRIPTION
**Pull request by pukapukan**
Upgrade deasync to address compatibility issue with node@9.3

https://github.com/abbr/deasync/issues/89

### CODE REVIEW

**Comment by giuseppeg** [comment]
thanks @pukapukan I will release later today!

**Comment by pukapukan** [comment]
thanks @giuseppeg !! 👍

**Comment by pukapukan** [comment]
hi @giuseppeg can you release the fix please :)

**Comment by giuseppeg** [comment]
@pukapukan published `0.1.2`

**Pull request merged**
