### PR TITLE
Updated dependencies, converted .postcssrc into a postcss.config.js, …

### PR DESCRIPTION
**Pull request by JosephScript**
…updated tests to use preset-env, added a new plugin test and converted old one into a features/browser feature test.

### CODE REVIEW

**Comment by JosephScript** [comment]
Hey everyone. I have updated this plugin to use `postcss-preset-env` instead of cssnext, which is being deprecated in favor of the former. In addition I updated the examples and fixed the tests, as well as added a new test to demonstrate how to use postcss features and plugins. Additionally, I rewrote the postcssrc into a postcss.config.js file which is the standard or at least more commonplace. ANd finally, I added a browserlist to the config to demonstrate how to do transformations using postcss-preset-env correctly. 

Let me know if you have any questions or concerns. And thanks for the great plugin!

**Comment by giuseppeg** [comment]
@NukaPunk super sorry for the late reply. Thanks for the contribution! Can you remove `package-lock.json`? I am not sure if keeping both yarn.lock and package-lock.json works (I may wrong and happy to change my mind). Since you are ugrading to Postcss 7, this should be a major release right?

**Comment by JosephScript** [comment]
I removed the `package-lock.json` and updated the `yarn.lock`. What version should we bump to, maybe 1.0.0?

**Comment by giuseppeg** [comment]
awesome thank you! @NukaPunk would you be interested in taking ownership of this repo? I don't use it and I don't have time to maintain it

**Comment by JosephScript** [comment]
Sure! I'm currently using it to develop a new app so I'd be more than happy.

**Comment by giuseppeg** [comment]
awesome I added you as collaborator and I just released 1.0.0

**Pull request merged**
